name: Linter Run Action

on:
  pull_request:
    types: [ synchronize, labeled ]
    branches:
      - '**'

jobs:
  detekt:
    name: Linter Run

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      actions: write
      pull-requests: write

    steps:

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Linter Run
        uses: alaegin/Detekt-Action@v1.22.0
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: linter/detekt_config.yml
          reviewdog_reporter: github-pr-review
          reviewdog_level: error
          fail_on_error: true

      - name: Validate Comments
        run: |
          comments_json=$(curl -s -H "Authorization: Bearer ${{ secrets.github_token }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/comments?per_page=100")
          has_errors=$(echo "$comments_json" | jq 'map(select(.line != null)) | length > 0')
          if [[ "$has_errors" == "true" ]]; then
            echo "PR has unresolved comments"
            exit 1
          fi
